name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: WebAssembly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown

      - name: Check format
        run: cargo fmt --check

      - name: Check
        run: cargo check --target wasm32-unknown-unknown --all-targets --all-features

      - name: Lint
        run: cargo clippy --target wasm32-unknown-unknown --all-targets --all-features -- -D warnings

      - name: Test parser
        run: cargo test --lib --all-features

      - name: Build release
        run: cargo build --release --target wasm32-unknown-unknown --all-features
